# Generated by Django 2.1.5 on 2019-02-14 02:45

import django.contrib.postgres.fields
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caregory', models.CharField(max_length=255)),
                ('number_of_bags', models.IntegerField()),
                ('location', models.CharField(max_length=255)),
                ('target', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), size=5)),
                ('institution', models.CharField(max_length=255)),
                ('address', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), size=4)),
                ('receipt_date', models.DateField()),
                ('receipt_time', models.TimeField()),
                ('note', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('target_mission', models.CharField(max_length=255)),
                ('things_categories', multiselectfield.db.fields.MultiSelectField(choices=[(1, 'ubrania'), (2, 'jedzenie'), (3, 'meble'), (4, 'zabawki'), (5, 'sprzęt AGD'), (6, 'książki')], max_length=11)),
            ],
        ),
    ]
