# Generated by Django 2.1.5 on 2019-02-19 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oddaj_rz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('genitive', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('genitive', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name='gift',
            old_name='number_of_bags',
            new_name='bags',
        ),
        migrations.RenameField(
            model_name='institution',
            old_name='target_mission',
            new_name='mission',
        ),
        migrations.RemoveField(
            model_name='gift',
            name='caregory',
        ),
        migrations.RemoveField(
            model_name='gift',
            name='location',
        ),
        migrations.RemoveField(
            model_name='institution',
            name='things_categories',
        ),
        migrations.AlterField(
            model_name='gift',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oddaj_rz.Institution'),
        ),
        migrations.AddField(
            model_name='gift',
            name='caregories',
            field=models.ManyToManyField(to='oddaj_rz.Category'),
        ),
        migrations.AddField(
            model_name='gift',
            name='locations',
            field=models.ManyToManyField(to='oddaj_rz.Location'),
        ),
        migrations.AddField(
            model_name='institution',
            name='categories',
            field=models.ManyToManyField(to='oddaj_rz.Category'),
        ),
        migrations.AddField(
            model_name='institution',
            name='locations',
            field=models.ManyToManyField(to='oddaj_rz.Location'),
        ),
    ]
